name: Build, pack and deploy to Azure public feed
on:
  workflow_dispatch:
env:
  NUGET_PACKAGE_PATH: ./published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 9.0.x
  WORKING_DIRECTORY: .
  PS_SOURCE_URL: "https://raw.githubusercontent.com/jsorling/miscscripts/main/github/actions"
  NUGET_AUTH_TOKEN: ${{ secrets.AZPUBLICFEEDPAT }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3.3.1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Set build info
      run: '& iex ((New-Object System.Net.WebClient).DownloadString("$env:PS_SOURCE_URL/buildinfo.ps1"))'
      shell: pwsh
    - name: Restore
      run: dotnet restore src/sqlexec/sqlexec.mapper.csproj
    - name: Pack
      run: dotnet pack src/sqlexec/sqlexec.mapper.csproj --configuration ${{ env.CONFIGURATION }} --no-restore --output "${{ env.NUGET_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4.6.1
      with:
        name: nugetpkg
        path: |
            ${{ env.NUGET_PACKAGE_PATH }}
            ./nuget.config
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.3.1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Download artifact from build job
      uses: actions/download-artifact@v4.1.9
      with:
        name: nugetpkg
        path: ${{ env.NUGET_PACKAGE_PATH }}
    - name: Push nuget
      run: dotnet nuget push --api-key AzureArtifacts --source sorling_public "${{ env.NUGET_PACKAGE_PATH }}/**/*.nupkg"
