name: Build and deploy to Azure public feed
on:
  workflow_dispatch:
env:
  NUGET_PACKAGE_PATH: ./published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: .
  PS_SOURCE_URL: "https://raw.githubusercontent.com/jsorling/miscscripts/main/github/actions"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Set build info
      run: '& iex ((New-Object System.Net.WebClient).DownloadString("$env:PS_SOURCE_URL/buildinfo.ps1"))'
      shell: pwsh
    - name: Restore
      run: dotnet restore src/sqlexec/sqlexec.mapper.csproj
    - name: Pack
      run: dotnet pack src/sqlexec/sqlexec.mapper.csproj --configuration ${{ env.CONFIGURATION }} --no-restore --output "${{ env.NUGET_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nugetpkg
        path: ${{ env.NUGET_PACKAGE_PATH }}
  deploy:
  # https://learn.microsoft.com/en-us/azure/devops/artifacts/quickstarts/github-actions?view=azure-devops
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: nugetpkg
        path: ${{ env.NUGET_PACKAGE_PATH }}
    - name: Set nuget add sources
      # nuget sources Add -Name azurepublic -Source https://pkgs.dev.azure.com/sorling/PublicFeed/_packaging/PublicFeed/nuget/v3/index.json -UserName "" -Password ${{ secrets.azpublicfeedpat }} -config <PATH_TO_NUGET_CONFIG_FILE>
      run: nuget sources Add -Name "azurepublic" -Source https://pkgs.dev.azure.com/sorling/PublicFeed/_packaging/PublicFeed/nuget/v3/index.json -UserName "" -Password ${{ secrets.azpublicfeedpat }}
    - name: Push nuget
      run: nuget push "${{ env.NUGET_PACKAGE_PATH }}/**/*.nupkg" -src azurepublic -ApiKey AZ
